CONFIG="~/.config"
ZSH="zsh"
NVIM="nvim"
alias zshconfig="$NVIM ~/.zshrc"
alias zsha="$NVIM $CONFIG/$ZSH/aliases.zsh"
alias zshe="$NVIM $CONFIG/$ZSH/env.zsh"
alias zshv="$NVIM $CONFIG/$ZSH/vi.zsh"
alias ohmyzsh="$NVIM ~/.oh-my-zsh"
alias proxy="export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890"
alias ala="$NVIM $CONFIG/alacritty/alacritty.yml"
