export ZSH="$HOME/.oh-my-zsh"
if test uname = "Darwin"; then
	export FZF_BASE="/opt/homebrew/opt/fzf"
else
fi

ZSH_THEME="robbyrussell"
# zsh plugins
plugins=(
        git
        zsh-autosuggestions
        vi-mode
        zsh-syntax-highlighting
        fzf

)
source $ZSH/oh-my-zsh.sh
